### ISSUE TITLE
Im REDAXO log gefunden, PHP 8

### ISSUE THREAD

**Issue by tyrant88** [AndiLeni/statistics#101]
stats_visit::__construct(): Argument #4 ($domain) must be of type string, null given, called in /var/www/sssssss/releases/228/src/addons/statistics/boot.php on line 95
	
src/addons/statistics/lib/stats_visit.php  line 73

**Comment by AndiLeni** [comment]
Komisch, dass rex_yrewrite::getHost() hier offenbar null liefert.

Hast du eine yRewrite Domain angelegt?
Bzw könntest vllt ins Project addon ein Log einfügen, damit man sieht, ob Besucher bei dir eine Domain gesetzt haben?
`rex_logger::logError(2, rex_yrewrite::getHost() ?? 'null', '', 1);`

**Comment by tyrant88** [comment]
$_SERVER['HTTP_HOST'] ist halt nicht immer gesetzt.

**Comment by AndiLeni** [comment]
Ja, ich war in der Annahme, dass rex_yrewrite::getHost() immer etwas liefert, aber dem ist nicht so.
Ich würde bei fehlendem Host die Domain auf einen leeren String setzen.

**Comment by tyrant88** [comment]
Ja, denke ich auch. Es ist einfach nicht auszuschließen. Hatte mich noch mal 3/4 ins Thema eingelesen, konnte aber nichts brauchbares ableiten.
