### ISSUE TITLE
Es wird eine Datei TEST.txt im public root Ordner angelegt

### ISSUE THREAD

**Issue by tyrant88** [AndiLeni/statistics#103]
![Zwischenablage-1](https://user-images.githubusercontent.com/1277494/230362942-a3d0bcfd-2082-49d7-b8bf-f53d4b7e23e3.jpg)

**Comment by AndiLeni** [comment]
Danke für den Hinweis! 
Da ist beim Debuggen wohl was übrig geblieben.
Ich habe den vendor in 2.6.1 aktualisiert, damit sollte dieses Problem auch weg sein.
