### ISSUE TITLE
Auto-Löschen nach x Monaten

### ISSUE THREAD

**Issue by iceman-fx** [AndiLeni/statistics#108]
Eine konfigurierbare Auto-Löschen-Funktion wäre ganz toll und wichtig, damit z.B. alle Einträge (aller Tabellen) die älter als 12 Monate sind automatisch gelöscht werden.

Grund:
Das DB-Backup wird bei mir aktuell ziemlich groß, wodurch der Rex-Cron abstürzt wegen zu langer Laufzeit/zu wenig Memory.
Allein 20 MB belegt bei mir nur das Statistik Addon in der DB.

**Comment by AndiLeni** [comment]
@iceman-fx  Welche Tabelle(n) des Statistik add-ons sind denn so groß bei dir? 
Kannst du das mal nachgucken?

**Comment by iceman-fx** [comment]
rex_pagestats_hash (6,9MB)
rex_pagestats_referer (4,7MB)
rex_pagestats_visits_per_url (8,9MB)

**Comment by AndiLeni** [comment]
Oh ja, die sind ganz schön groß.
Ein Cronjob wird mitgeliefert um die hash tabelle zu leeren. Die kann täglich geleert werden.
Und für die anderen Tabellen kann man bestimmt einen einfachen Cronjob schreiben, der per rex_sql einfach in allen Tabellen mit Datum die ältesten löscht.

**Comment by alxndr-w** [comment]
https://github.com/alexplusde/auto_delete hier könnte man sich eine Lösung abschauen, generell ist das Löschen alter Daten über einen PHP-Cronjob ein No-Brainer.

(Und was sind 15 MB in einer Datenbank? Ab 2 GB wird's interessant!)
