### ISSUE TITLE
API Abruf einzelner Statistikdaten

### ISSUE THREAD

**Issue by iceman-fx** [AndiLeni/statistics#111]
Eine einfache Abrufmöglichkeit für Statistikdaten aller Domains oder nur einer einzelnen Domain per API Aufruf wäre toll, um z.b. die Zugriffe der letzten 30 Tage oder der letzten 12 Monate im Dashboard oder im Frontend anzeigen zu können.

Der Abruf soll jetzt nicht alles darstellen, aber z.b. die Gesamtzahl der Zugriffe und Benutzer für die Domain XYZ in den letzten 30 Tagen.

**Comment by alxndr-w** [comment]
Eine Umstellung auf YForm wäre eine zweckdienliche Möglichkeit - und so sehr ich YForm liebe, hier sehe ich das nicht.

Du kannst aber in deinem Projekt die Tabellen zu YForm-Tabellen migrieren und die REST Api nutzen.

Eine weitere Möglichkeit ist, dir eine eigene API zu schreiben, bspw. über die REX API.

Die dritte Möglichkeit zur Auswertung in externen Tools ist ein separater Datenbank-Nutzer mit Lesezugriff auf die Tabellen, z.B. zur Auswertung in Google Looker Studio oder über Google Sheets und Google Apps Script.

Habe ich eben erst selbst gemacht, weil ich Bedarf hatte.

Fazit für mich: Hier gibt es 3 mögliche Lösungswege, die nicht im Addon erneut gelöst werden müssten.
