### ISSUE TITLE
Warning im Log: preg_match(): Unknown modifier 'c'

### ISSUE THREAD

**Issue by iceman-fx** [AndiLeni/statistics#113]
Mit der aktuellen Version erhalte ich unter PHP 8.2 derzeit jede Menge der folgenden Fehlerausgaben im Rex-Log:

preg_match(): Unknown modifier 'c'
Datei: redaxo/src/addons/statistics/lib/Visit.php:166

**Comment by AndiLeni** [comment]
Was sind denn die Variablen die preg_match hier versucht zu verarbeiten?
`preg_match($regex, $this->url)` das sind einmal die regex ausnahmen die du selbst angelegt hast sowie die aufgerufene url.
Da muss irgend eine komische Eingabe dabei sein.

**Comment by iceman-fx** [comment]
Diese suchstrings habe ich hinterlegt:

webvisitenkarte.cth-riesa.de/7203e789-0152-4214-b9b7-0cf7bff89ba9
webvisitenkarte.cth-riesa.de/59b3bcb2-e168-430c-87d5-fe614b35614f
demo-gs.webvisitenkarte.cth-riesa.de/.env
demo-gs.webvisitenkarte.cth-riesa.de/.git/config
demo-gs.webvisitenkarte.cth-riesa.de/api/.env
webvisitenkarte.cth-riesa.de/.git/config
demo.webvisitenkarte.cth-riesa.de/.git/config
webvisitenkarte.cth-riesa.de/site.webmanifest
webvisitenkarte.cth-riesa.de/assets/RobotoCondensed-Light.woff2
webvisitenkarte.cth-riesa.de/webfonts/fa-brands-400.ttf
webvisitenkarte.cth-riesa.de/assets/Poppins-ExtraBold.woff
webvisitenkarte.cth-riesa.de/assets/Roboto-Light.woff2
webvisitenkarte.cth-riesa.de/assets/Poppins-ExtraBold.woff2
webvisitenkarte.cth-riesa.de/assets/Roboto-Regular.woff2
webvisitenkarte.cth-riesa.de/webfonts/fa-solid-900.ttf
webvisitenkarte.cth-riesa.de/webfonts/fa-brands-400.woff
webvisitenkarte.cth-riesa.de/favicon-16x16.png
webvisitenkarte.cth-riesa.de/assets/Roboto-Regular.woff
webvisitenkarte.cth-riesa.de/webfonts/fa-solid-900.woff
webvisitenkarte.cth-riesa.de/assets/RobotoCondensed-Light.woff
webvisitenkarte.cth-riesa.de/webfonts/fa-brands-400.woff2
webvisitenkarte.cth-riesa.de/assets/Roboto-Light.woff
webvisitenkarte.cth-riesa.de/webfonts/fa-solid-900.woff2
webvisitenkarte.cth-riesa.de/favicon-32x32.png
webvisitenkarte.cth-riesa.de/apple-touch-icon.png
webvisitenkarte.cth-riesa.de/ads.txt
webvisitenkarte.cth-riesa.de/wwwroot.7z
webvisitenkarte.cth-riesa.de/www.rar
webvisitenkarte.cth-riesa.de/cth-riesa.tar.gz
webvisitenkarte.cth-riesa.de/wwwroot.rar
webvisitenkarte.cth-riesa.de/cth-riesa.de.tar.gz
webvisitenkarte.cth-riesa.de/root.tar
webvisitenkarte.cth-riesa.de/webvisitenkartecth-riesade.rar
webvisitenkarte.cth-riesa.de/cth-riesa.tar
webvisitenkarte.cth-riesa.de/sql.tar.gz
webvisitenkarte.cth-riesa.de/wwwroot.sql
webvisitenkarte.cth-riesa.de/webvisitenkartecth-riesade.tar.gz
webvisitenkarte.cth-riesa.de/cth-riesa.de.zip
webvisitenkarte.cth-riesa.de/web.tar.gz
webvisitenkarte.cth-riesa.de/webvisitenkarte_cth-riesa_de.sql
webvisitenkarte.cth-riesa.de/webvisitenkarte_cth-riesa_de.zip
webvisitenkarte.cth-riesa.de/webvisitenkartecth-riesade.tar
webvisitenkarte.cth-riesa.de/website.tar
webvisitenkarte.cth-riesa.de/website.7z
webvisitenkarte.cth-riesa.de/www.sql
webvisitenkarte.cth-riesa.de/wwwroot.tar
webvisitenkarte.cth-riesa.de/sql.rar
webvisitenkarte.cth-riesa.de/webvisitenkarte_cth-riesa_de.tar
webvisitenkarte.cth-riesa.de/web.sql
webvisitenkarte.cth-riesa.de/site.tar.gz
webvisitenkarte.cth-riesa.de/cth-riesa.de.rar
webvisitenkarte.cth-riesa.de/www.zip
webvisitenkarte.cth-riesa.de/sql.tar
webvisitenkarte.cth-riesa.de/cth-riesa.sql
webvisitenkarte.cth-riesa.de/webvisitenkarte.cth-riesa.de.sql
webvisitenkarte.cth-riesa.de/webvisitenkartecth-riesade.zip
webvisitenkarte.cth-riesa.de/webvisitenkarte.cth-riesa.de.tar
webvisitenkarte.cth-riesa.de/site.tar
webvisitenkarte.cth-riesa.de/www.7z
webvisitenkarte.cth-riesa.de/webvisitenkarte_cth-riesa_de.7z
webvisitenkarte.cth-riesa.de/cth-riesa.de.7z
webvisitenkarte.cth-riesa.de/web.zip
webvisitenkarte.cth-riesa.de/web.tar
webvisitenkarte.cth-riesa.de/www.tar.gz
webvisitenkarte.cth-riesa.de/webvisitenkarte_cth-riesa_de.tar.gz
webvisitenkarte.cth-riesa.de/site.sql
webvisitenkarte.cth-riesa.de/root.rar
webvisitenkarte.cth-riesa.de/cth-riesa.de.sql
webvisitenkarte.cth-riesa.de/root.tar.gz
webvisitenkarte.cth-riesa.de/webvisitenkartecth-riesade.7z
webvisitenkarte.cth-riesa.de/wwwroot.tar.gz
webvisitenkarte.cth-riesa.de/webvisitenkarte.cth-riesa.de.tar.gz
webvisitenkarte.cth-riesa.de/webvisitenkarte_cth-riesa_de.rar
webvisitenkarte.cth-riesa.de/website.tar.gz
webvisitenkarte.cth-riesa.de/site.7z
webvisitenkarte.cth-riesa.de/sql.7z
webvisitenkarte.cth-riesa.de/www.tar
webvisitenkarte.cth-riesa.de/cth-riesa.zip
webvisitenkarte.cth-riesa.de/root.zip
webvisitenkarte.cth-riesa.de/cth-riesa.rar
webvisitenkarte.cth-riesa.de/site.rar
webvisitenkarte.cth-riesa.de/sql.zip
webvisitenkarte.cth-riesa.de/webvisitenkarte.cth-riesa.de.zip
webvisitenkarte.cth-riesa.de/sql.sql
webvisitenkarte.cth-riesa.de/wwwroot.zip
webvisitenkarte.cth-riesa.de/site.zip
webvisitenkarte.cth-riesa.de/root.7z
webvisitenkarte.cth-riesa.de/cth-riesa.7z
webvisitenkarte.cth-riesa.de/website.zip
webvisitenkarte.cth-riesa.de/webvisitenkartecth-riesade.sql
webvisitenkarte.cth-riesa.de/root.sql
kgvdimmelsberg.de/modules/mod_simplefileuploadv1.3/elements/%C2%AE.php7
kgvdimmelsberg.de/kgvdimmelsberg.de.bz2
kgvdimmelsberg.de/kgvdimmelsberg.de.tar.bz2
kgvdimmelsberg.de/.git/config
kgvdimmelsberg.de/wp-content/plugins/wordpresscore/include.php
kgvdimmelsberg.de/uploads.tar.bz2
kgvdimmelsberg.de/app.tar.bz2

**Comment by AndiLeni** [comment]
@iceman-fx hast du hier auch etwas hinterlegt?
![image](https://github.com/AndiLeni/statistics/assets/13385771/c73f9f88-9f32-43b6-8433-9a49b21d425d)

**Comment by AndiLeni** [comment]
@iceman-fx 
Du hast all diese Strings so wie du sie hier eingefügt hast einfach in das "Zu ignorierende REGEX:" geschrieben, oder?
Da musst du die Strings anpassen, denn in dieses Feld dürfen nur korrekte regex pattern eingefügt werden.

Ein Problem sind fehlende slashes die das pattern begrenzen. Also z.b. müsste `webvisitenkarte.cth-riesa.de/site.zip` so aussehen `/webvisitenkarte.cth-riesa.de/site.zip/` um die warning `preg_match(): Delimiter must not be alphanumeric or backslash` zu unterbinden.

Und dann müssen die bestehenden slashes escaped werden `/webvisitenkarte.cth-riesa.de\\/site.zip/`

Das sollte funktionieren:
```
<?php

$pattern = "/webvisitenkarte.cth-riesa.de\\/site.zip/"; // Hier ist 'c' fälschlicherweise als Modifikator verwendet
$string = "webvisitenkarte.cth-riesa.de/site.zip";

if (preg_match($pattern, $string)) {
    echo "Das Muster wurde gefunden.";
} else {
    echo "Das Muster wurde nicht gefunden.";
}
```

Vielleicht recht es für deinen fall aber auch schon, wenn du die Strings in das Feld "Zu ignorierende Pfade:" statt zu den regex hinzufügst.

**Comment by iceman-fx** [comment]
@AndiLeni Nein. Die Pfade stehen im ersten Feld (siehe Screenshot).
![1](https://github.com/AndiLeni/statistics/assets/4291047/1b34f512-6809-4d0a-a8c7-3410ac7bff01)

**Comment by iceman-fx** [comment]
Hier noch ein Screenshot der Logs:

![2](https://github.com/AndiLeni/statistics/assets/4291047/f5af13d3-3c2b-4076-9205-415466ca212b)

**Comment by alxndr-w** [comment]
![image](https://github.com/user-attachments/assets/a74f04f5-77dc-439e-9e23-df35d42eb038)
