### ISSUE TITLE
addon lässt sich nicht mehr aufrufen

### ISSUE THREAD

**Issue by ansichtsache** [AndiLeni/statistics#117]
`Error while executing statement "select lastpage , count(*) as 'count' from rex_pagestats_sessionstats group by lastpage order by count desc;" using params []! SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'xxxx.de/aktuell/aspa-news-archiv-mit-news-bis-2014/weihnachts' for key '/tmp/#sql3c94b5_15d8cc_c.<group_key>'`

**Comment by alxndr-w** [comment]
Ich hatte das Problem auch 1x mit einem doppelten Eintrag, weiß jedoch nicht, wie dieser zustande kam. Zur Lösung deines Problems bitte direkt in Adminer den Datensatz aus `rex_pagestats_sessionstats` entfernen.
