### ISSUE TITLE
Class "filterDateHelper" not found

### ISSUE THREAD

**Issue by iceman-fx** [AndiLeni/statistics#118]
In einer frischen Installation kommt obiger Fehler beim Aufruf des Punktes Kampagnen.

Error 
…/redaxo/src/addons/statistics/plugins/api/pages/campaigns.php:11

**Comment by iceman-fx** [comment]
Nachtrag:
Anscheinend ist der Punkt "Kampagnen" das Plugin, welches aber teilweise bereits im Hauptaddon integriert ist als "Events".
Jedoch ohne das Plugin funktioniert der Eventbereich nicht, da das Plugin erst die benötige Datenbanktabelle installiert.

**Comment by AndiLeni** [comment]
@iceman-fx Da passt irgendwas nicht 🤔
Den Punkt "Kampagnen" gibt es schon lange nicht mehr, er heißt nun "Events".
Die ganzen Plugins wurden auch in das Haupt Addon integriert.
Werden dir in der Addon Übersichtsseite noch Plugins angezeigt?

**Comment by iceman-fx** [comment]
Ja, werden sie.
Dann kann ich bei mir ja einfach die Plugin-Ordner löschen?

Komisch ist halt nur, dass es mit deinstallierten Plugins auch Fehler bzgl. der Datenbanktabelle gibt.

**Comment by AndiLeni** [comment]
> Dann kann ich bei mir ja einfach die Plugin-Ordner löschen?

Ja, das sollte kein Problem ein. Eigentlich dürfte der Ordner gar nicht existieren, sowohl bei Neuinstallation als auch bei Update sollte der gelöscht werden.

**Comment by alxndr-w** [comment]
Plugins werden nicht automatisch gelöscht beim Update.

Aber laut https://github.com/AndiLeni/statistics/blame/main/update.php#L25 ist das seit Mai 2023 der Fall, wenn das Addon über den Installer aufgerufen wird und damit die update.php ausgeführt wurde.

Andernfalls das Addon reinstallieren. Sollte es hier noch Probleme geben, mache ich gerne wieder auf.
