### ISSUE TITLE
keine Daten

### ISSUE THREAD

**Issue by ynamite** [AndiLeni/statistics#124]
Version 3.1.0 des Addons ist installiert, aber es werden keine Daten in die Tabellen geschrieben und somit bleibt die Statistik leer.
Im Log steht auch nichts. Irgendeine Ahnung, was hier los sein könnte?
Ich verwende das Addon in einer R5.11er Version. Ist die allenfalls zu alt?

**Comment by AndiLeni** [comment]
rex_request ist erst ab redaxo 5.12 verfügbar. 
Die package.yml muss angepasst werden und redaxo 5.12 fordern als mindestversion
