### ISSUE TITLE
Tabellen werden riesig

### ISSUE THREAD

**Issue by VIEWSION** [AndiLeni/statistics#126]
Hi,

ich hab das Problem dass die Tabellen ungewöhnlich groß werden. Das AddOn ist jetzt ca. 1 Jahr aktiv und allein die [rex_pagestats_sessionstats](https://labelisten.com/redaxo/index.php?page=adminer&username=&db=c201_wp01&table=rex_pagestats_sessionstats) hat schon fast 150MB. Kann das sein?

<img width="1133" alt="image" src="https://github.com/user-attachments/assets/133afcab-4226-4595-b29f-d20a1822b42d">

Danke!

**Comment by AndiLeni** [comment]
Ja, das ist (leider) so. 
Die sessionstats kann ich im Gegensatz zu den anderen Statistiken nicht direkt beim Besuch der Seite aggregieren sondern muss für jeden Aufruf einen Eintrag in der Tabelle anlegen.

**Comment by VIEWSION** [comment]
Ok - Wie könnte man das optimieren? Wenn ich das über mehrere Jahre laufen lassen möchte, wird das so nicht mehr funktionieren. Man bräuchte wohl so eine Art Archivierung.... Ich hab mir ehrlich gesagt noch nicht genau angesehen wie das technisch funktioniert, aber ich kann mich da gerne mit einbringen.

**Comment by VIEWSION** [comment]
Hmm... Ok - ich check das mal mit Matomo. Was mir halt gefällt ist die Tatsache dass man mit deinem AddOn im Frontend nicht erkennen kann ob da ein Tracker läuft. Bei Matomo wird ja standardmäßig ein JS geladen... aber ich glaube da gibt es auch eine Alternative über PHP... muss ich mal testen. Danke!

**Comment by AndiLeni** [comment]
@VIEWSION schau mal hier, es gibt einen PHP Tracker für Matomo.
https://github.com/matomo-org/matomo-php-tracker/ und https://developer.matomo.org/api-reference/PHP-Matomo-Tracker.
Da kannst du bestimmt relativ einfach im Projekt-Addon damit einen Request absetzen wenn ein Seitenaufruf stattfindet.

**Comment by alxndr-w** [comment]
Folgende Optimierungen sind auf Datenbankebene möglich:

1. Hash-Felder benötigen nicht varchar(255), sondern varchar(40) oder char
2. Gleiches gilt für rex_pagestats_sessionstats.token
3. rex_pagestats_bot alle varchar-Felder können kürzer
4. rex_pagestats_data.type könnte enum/set sein
5. rex_pagestats_sessionstats.visitduration und .pagecount könnten int(5) unsigned oder kleiner sein
6. rex_pagestats_referer.referer könnte vermutlich kürzer sein varchar(255), die Information wird praktisch nicht benötigt wenn im Wesentlichen die Domain interessant ist.
7. rex_pagestats_urlstatus.status könnte varchar(24) sein oder nur int(3) unsigend für den HTTP-Statuscode

**Comment by alxndr-w** [comment]
Das gesagt sind 150 für eine Datenbank doch ein Klacks. Da brauchst du mehr als 10 Jahre, bis die Datenbank an den 2 GB kratzt.

**Comment by alxndr-w** [comment]
Weiter geht's in #115
