### ISSUE TITLE
Wunsch: Referrer loggen und ausgeben 

### ISSUE THREAD

**Issue by iceman-fx** [AndiLeni/statistics#29]
Es wäre noch toll, wenn die Referrer mitgeloggt werden würden, wenn der Aufruf von einer externen Seite (z.b. Google Suche) kommt.

**Comment by TobiasKrais** [comment]
Funktioniert. Frage: soll die eigene Seite auch als Referrer gelistet werden? Das ist im Moment der Fall.

**Comment by TobiasKrais** [comment]
Und es werden auch die Parameter der Referrer geloggt. Auch hier die Frage, ob das nötig ist.

**Comment by iceman-fx** [comment]
Es machen eigentlich nur die externen Seiten Sinn, da man damit Rückschlüsse auf Backlinks etc. Ziehen kann.

**Comment by iceman-fx** [comment]
Parameter ist sehr gut, um evtl. Such-querys auswerten zu können.

**Comment by AndiLeni** [comment]
Dann lasse ich mal das gesamte Query drin.

In https://github.com/AndiLeni/statistics/commit/42503aa951153577abb9ba341810e739e3c21c21 ist ne Überprüfung drin, ob die Referrer URL mit der eigenen URL anfängt. Falls ja, wird der Referer nicht gespeichert.
