### ISSUE TITLE
Statistik bremst PHP-Bearbeitung

### ISSUE THREAD

**Issue by skerbis** [AndiLeni/statistics#31]
Auf einer meiner Sites getestet: 

1500 ms mit diesem AddOn
678ms ohne. 

package_boot_statistics braucht alleine 528ms
Dazu addieren sich noch Aufrufe je Mediamanager-File, mit jeweils 544ms. 

Der Websiteaufbau wird extrem verlangsamt

**Comment by TobiasKrais** [comment]
Hast du mal die neueste Version installiert und das media Plugin deaktiviert? Da müsste der Speed wieder OK sein.

**Comment by AndiLeni** [comment]
@skerbis Könntest du das nochmal mit dem aktuellen Stand überprüfen?
Ohne das Media Plugin sollte jetzt gar keine Verzögerung der Ladezeit mehr durch das Addon stattfinden.

![grafik](https://user-images.githubusercontent.com/13385771/124363278-94f17c80-dc3a-11eb-8a3f-46f9f2e3187f.png)

**Comment by TobiasKrais** [comment]
Erfolgreich getestet. Kannst du auch schließen.

**Comment by skerbis** [comment]
Jupp , danke
