### ISSUE TITLE
PHP Notices in aktueller Version

### ISSUE THREAD

**Issue by iceman-fx** [AndiLeni/statistics#41]
![Unbenannt](https://user-images.githubusercontent.com/4291047/124874315-ddf15a00-dfc7-11eb-8a2f-53047af5f48e.PNG)

**Comment by iceman-fx** [comment]
Die Notices gibt es auch in der aktuellen Version noch.

**Comment by AndiLeni** [comment]
Unter welcher PHP Version erscheinen die Notices denn?
Apache oder Nginx?

**Comment by iceman-fx** [comment]
PHP 7.3.25

**Comment by iceman-fx** [comment]
Klappt jetzt bei mir ;-)
