### ISSUE TITLE
Hilfe im Addon vorsehen

### ISSUE THREAD

**Issue by iceman-fx** [AndiLeni/statistics#42]
Die Hilfe zur Nutzung der Plugins etc. würde ich noch als Tab mit in das Addon aufnehmen (rechts ausgerichtet).

**Comment by iceman-fx** [comment]
Hilfe ist da, allerdings werden die eingebundenen Vorschaubilder nicht angezeigt.
Grund: die Pfadangabe der Bilder ist falsch.

./preview/1.png wird zu domain.de/redaxo/preview/1.png

**Comment by AndiLeni** [comment]
Ich habe keinen ordentlichen Weg gefunden, dass die Bilder sowohl in der Hilfeseite als auch auf Github angezeigt werden.
Im Assets Ordner sind sie auch irgendwie fehl am Platz.
Aber da man sie in der Hilfeseite auch nicht unbedingt braucht würde ich sie da einfach weg lassen.

**Comment by iceman-fx** [comment]
Ja. Ist ok.
Die Bilder müssen in den assets Ordner, welcher beim install automatisch in den öffentlichen Bereich kopiert wird.
Dann kann man die von dort direkt einbinden.
