### ISSUE TITLE
Ignorierpfade erweitern, so dass Suchphrasen ignoriert werden können

### ISSUE THREAD

**Issue by iceman-fx** [AndiLeni/statistics#43]
Durch Deine tolle Statistik bekomme ich gerade bei einige Webseiten mit, was alles versucht wird, um in die Seite einsteigen zu können oder um dort nicht gewollte Aufrufe zu testen.

Es wäre jetzt schön, wenn man in der Ignorierliste auch Suchphrasen hinterlegen könnte.
![ScreenHunter 235](https://user-images.githubusercontent.com/4291047/125204967-23d84780-e280-11eb-9431-3e164fc39fb0.png)

Irgendwie müsste man dann zusätzlich noch eine kleine Funktion einbauen, um alle gefundenen Ignorierwerte aus den Statistiken löschen zu können, ohne die gesamte Statistik leeren zu müssen.

Hier ein Beispiel aus der Statistik, was da gerade bei einer Webseite so abläuft:

![ScreenHunter 234](https://user-images.githubusercontent.com/4291047/125204854-8c72f480-e27f-11eb-8c3f-543d58b353ca.png)

**Comment by iceman-fx** [comment]
Ich habe es gerade mal getestet, aber noch nicht hinbekommen, dass es klappt.
Muss ich einen kompletten Regex definieren oder reicht nur ein Teil, wie z.B.: .*schutz.*

**Comment by AndiLeni** [comment]
Es muss eine vollständige Regex Expression angegeben werden.
Die eingetragenen Ausdrücke werden direkt als pattern verwendet.

**Comment by iceman-fx** [comment]
Du musst mir mal dazu bitte einen Tipp geben.

Wenn ich als Regex dies hinterlege: /.\*schutz.\*/i
dann sollte doch folgende URL "https://www.kueche-aktiv-sachsen.de/datenschutz.html" nicht aufgezeichnet werden.
Wird sie aber.

**Comment by AndiLeni** [comment]
Der Fehler könnte damit behoben sein, falls du auf einem Mac arbeitest.
Wenn nicht müssen wir nochmal schauen wo es klemmt.

**Comment by iceman-fx** [comment]
Klappt leider nicht.
Es wird immer noch geloggt.

Ich arbeite zwar an einem Windows-PC, aber dies sollte dem Logging egal sein, da dies ja auf der Webseite über den Webserver erfolgt.

**Comment by iceman-fx** [comment]
Fehler gefunden in stats_visits.php.
dies:

`if (preg_match($regex, $this->url) === true) {`

tauschen mit:

`if (preg_match($regex, $this->url) == true) {`
