### ISSUE TITLE
2 kleine Schönheitsfehler ;-)

### ISSUE THREAD

**Issue by iceman-fx** [AndiLeni/statistics#45]
Bei Klick auf die Pagination und dem folgenden Laden der neuen Inhalte, sollte man immer an den Tabellenanfang hochfahren/springen.

Lange Texte bzw. URLs sollten umbrechen. Ist per CSS einfach zu machen.

![1](https://user-images.githubusercontent.com/4291047/125205149-25563f80-e281-11eb-873f-a38c1915067c.PNG)

**Comment by AndiLeni** [comment]
Ich habe mit 0bf40f7 Javascript code hinzugefügt mit welchem an die passenden Stellen gescrollt wird.
Aber ich mag es persönlich nicht wenn ein Link für mich die Entscheidung trifft wo ich hinscrollen muss, deshalb ist der Code auskommentiert und kann bei Bedarf aktiviert werden.

**Comment by iceman-fx** [comment]
OK. Kannst du dies evtl. Als Option in den Einstellungen vorsehen, damit man dies nicht im Code ändern muss?
Bei einem Update deines Addons könnte sonst diese Änderung wieder rausfallen.

**Comment by iceman-fx** [comment]
Die Option habe ich gefunden und auch gleich alle Einstellungen getestet.
Leider sehe ich da zwischen den E. keinen Unterschied.
Die Tabelle fährt nicht an den Anfang, egal welche E. ich nutze.

Auch werden lange URLs nicht umgebrochen.
Kannst Du bitte nochmal schauen?
Dies hier würde Abhilfe schaffen:
```
table.table-bordered.dataTable th, table.table-bordered.dataTable td {
    border-left-width: 0;
    word-break: break-all;
}
```

**Comment by AndiLeni** [comment]
Hilft es, wenn du den Ordner `redaxo\assets\addons\statistics` löscht und dann das Addon nochmal installierst?

**Comment by iceman-fx** [comment]
Ja, nach dem Neuinstall klappt es nun.
