### ISSUE TITLE
Lösung gesucht für unzählige geloggte 404-Aufrufe

### ISSUE THREAD

**Issue by iceman-fx** [AndiLeni/statistics#47]
Ich habe Dein addon jetzt seit 1 Woche auf einer ganz gut besuchten Seite im Einsatz.
Leider werden aktuell unzählige falsch-Einträge geloggt, welche auf die das yRewrite und der 404-Seite zurückzuführen ist.

Auszug aus der Liste (ca. 200 solche Einträge):
![1](https://user-images.githubusercontent.com/4291047/125579225-3007a9c9-9c25-461b-a2f6-41cadff4db5d.PNG)

Irgendwie müsste man dies bereits vor dem loggen abblocken.

Eine Idee dazu:
Den Statuscode der aufgerufenen Seite prüfen, ob dieser "nicht 200" ist.
Damit würde man nur alle Seiten loggen, welche auch wirklich aufrufbar wären.

Optional kann man ja eine Option vorsehen, um auf Wunsch doch alle Aufrufe (inkl. 404) zu loggen.

Was denkst Du?

**Comment by AndiLeni** [comment]
Besteht denn die Möglichkeit, für einen Seitenaufruf den Statuscode zu überprüfen?
Einen extra curl Request würde ich nicht nutzen, damit würde man sich selber unnötigen Traffic erzeugen.

**Comment by iceman-fx** [comment]
Ja, mittels curl oder https://www.php.net/manual/en/function.http-response-code.php sollte dies klappen.
