### ISSUE TITLE
Einige Ressourcen werden nicht gefunden

### ISSUE THREAD

**Issue by iceman-fx** [AndiLeni/statistics#48]
index.php:1 
Refused to apply style from 'https://www.kueche-aktiv-sachsen.de/assets/addons/statistics/statistics.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

index.php:513 
GET https://www.kueche-aktiv-sachsen.de/assets/addons/statistics/statistics.js net::ERR_ABORTED 404 (Not Found)

index.php:1 
Refused to apply style from 'https://www.kueche-aktiv-sachsen.de/assets/addons/statistics/statistics.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

**Comment by AndiLeni** [comment]
Ist der Fehler noch aktuell?
Vllt. wurde er mit 1fde0ab behoben.

**Comment by iceman-fx** [comment]
Ja. Hatte es gestern erst nochmal getestet.

**Comment by AndiLeni** [comment]
Und nach dem Commit heute?
Eventuell musst du die Einträge in den settings nochmal speichern, damit sie korrekt angelegt werden.

**Comment by iceman-fx** [comment]
Moin.
Habe nun das aktuelle Release drin.
Leider klappt es mit den Ressourcen immer noch nicht.

```
Refused to apply style from 'https://www.kueche-aktiv-sachsen.de/assets/addons/statistics/statistics.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
index.php:67 GET https://www.kueche-aktiv-sachsen.de/assets/addons/statistics/statistics_scroll_table.js net::ERR_ABORTED 404 (Not Found)
index.php:67 GET https://www.kueche-aktiv-sachsen.de/assets/addons/statistics/statistics_scroll_table.js net::ERR_ABORTED 404 (Not Found)
```

**Comment by AndiLeni** [comment]
Unter `https://www.kueche-aktiv-sachsen.de/assets/addons/statistics/statistics.css` bekomme ich auch kein css sondern eine 404 Fehlerseite.
Ich glaube nicht, dass das Problem beim Addon liegt.

**Comment by iceman-fx** [comment]
Ich habe es jetzt nochmal komplett neu installiert.
Bisher keine Meldungen zu fehlenden Dateien.
