### ISSUE TITLE
Kleiner Darstellungsfehler auf Tablet

### ISSUE THREAD

**Issue by iceman-fx** [AndiLeni/statistics#50]
![Screenshot_20210726-200644_Chrome](https://user-images.githubusercontent.com/4291047/127101354-a49d97de-c17a-48dc-b100-7c1bc2ee57fd.jpg)

**Comment by iceman-fx** [comment]
Mögliche Lösung...

anstatt:
`<div id="DataTables_Table_5_filter" class="dataTables_filter"><label>Suchen:</label><input type="search" class="form-control input-sm" placeholder="" aria-controls="DataTables_Table_5" style=""></div>`

dies:
`<div id="DataTables_Table_5_filter" class="dataTables_filter"><input type="search" class="form-control input-sm" placeholder="" aria-controls="DataTables_Table_5" style="" placeholder="Suchen"></div>`

**Comment by iceman-fx** [comment]
Dieser Schönheitsfehler ist auch in der aktuellen Version von gestern noch drin.

Aber sonst alles tippi toppi.
Aktuell habe ich keine Anmerkungen mehr und das Addon könnte theoretisch in den Installer.

**Comment by iceman-fx** [comment]
Dieser Schönheitsfehler ist auch in der aktuellen Version noch drin.
Da bricht leider nix um, wenn der Platz nicht mehr ausreicht.

**Comment by iceman-fx** [comment]
Das Suchfeld passt auch in der aktuellen Version noch nicht rein (siehe Screenshot oben).

**Comment by AndiLeni** [comment]
Da wäre ich über einen Tipp sehr dankbar. Ich weiß leider nicht, wieso das Eingabefeld sich nicht an die maximale Breite hält.

**Comment by iceman-fx** [comment]
Das Problem ist das Label mit white-space: nowrap vor dem Eingabefeld.
Damit kann das Eingabefeld sich nicht mehr autom. in der Breite anpassen bzw. in der Zeile umbrechen und wird nach rechts gedrückt.

Deshalb meine Empfehlung, das Label weg zu machen und es als placeholder="Suchen" in das Eingabefeld zu setzen.

**Comment by AndiLeni** [comment]
@iceman-fx kann dieses issue geschlossen werden? Oder siehst du noch irgendwo UI Probleme?

**Comment by iceman-fx** [comment]
Es passt soweit.
Sicherlich kann man hier und da noch etwas optimieren, aber das ist aktuell alles nicht weltbewegend.
