### ISSUE TITLE
URL codiderte URLs korrekt darstellen

### ISSUE THREAD

**Issue by TobiasKrais** [AndiLeni/statistics#52]
Auf meiner Webseite habe ich russische und chinesische URLs. Diese werden unschön dargestellt:
![Bildschirmfoto von 2021-07-31 21-09-49](https://user-images.githubusercontent.com/4131072/127750220-ee22311b-5381-4423-b8e5-a9755fc19206.png)

Du URLs sollten URL decodiert dargestellt werden, damit sie leserlich sind.

**Comment by TobiasKrais** [comment]
Gleiches gilt auch für die Darstellung in der Grafik: 
![Bildschirmfoto von 2021-07-31 21-12-42](https://user-images.githubusercontent.com/4131072/127750232-d9cde37b-b037-4f76-93d2-c8f6b1af12e8.png)

**Comment by AndiLeni** [comment]
@TobiasKrais Hat der Fix das Problem behoben? Neue Einträge sollten nun decodiert gespeichert werden.

**Comment by TobiasKrais** [comment]
Ja. Neue URLs werden korrekt gespeichert. Falsch gespeicherte URLs bleiben falsch in der DB.

**Comment by TobiasKrais** [comment]
Wobei von meinen 175 Chinesischen URLs sind gerade mal 2 korrekt in der DB gespeichert werden, obwohl ich den Patch son seit Veröffentlichung der ersten Version im Installer drin hab. Optimal ware in Script, das einmalig beim Update des Adons die URLs korrigiert und die URLs ggf. zusammenführt, falls sie in 2 Schreibweisen vorliegen.

**Comment by AndiLeni** [comment]
Kannst du nachvollziehen wieso die nicht stimmen? Werden sie nicht korrekt decodiert, oder passiert der Fehler wo anders?

Das Ändern der vorhandenen Einträge würde ich nicht machen. Es klingt nach viel Arbeit für ein Problem, welches zukünftig nicht mehr auftreten sollte. 
Da auch noch nicht mit 1.0.0 released wurde, kann es durchaus noch zu solchen Breaking Changes kommen imho.

**Comment by TobiasKrais** [comment]
Für die Nachwelt dokumentiert: das hier wäre das Updateskript:
```
$result = \rex_sql::factory();
$result->setQuery("SELECT * FROM ". \rex::getTablePrefix() ."pagestats_dump;");
		
for($i = 0; $i < $result->getRows(); $i++) {
	$sql = \rex_sql::factory();
	if(urldecode($result->getValue("url")) !== $result->getValue("url")) {
		$sql->setQuery("UPDATE ". \rex::getTablePrefix() ."pagestats_dump SET `url`= '". urldecode($result->getValue("url")) ."' WHERE `url` = '". $result->getValue("url") ."'");
	}
	$result->next();
}
```

Aber bitte nicht einbauen, da sich in meiner DB URLs befinden, die es gar nicht im System gibt und das Update Skript zum Absturz bringen.

Ich muss jetzt mal beobachten, ob neue URLs nur noch korrekt codiert in der DB landen.

Wie gerade schon erwähnt sind bei mir viele URLs in der DB, die gar nicht im System vorhanden sind. Auch URLs mit Parametern sind vorhanden. Beides würde ich gerne vermeiden, Vor allem erstere URLs blähen die DB massiv auf und sind für das Marketing uninteressant.

**Comment by AndiLeni** [comment]
Es gibt eine Einstellung mit der Seitenaufrufe die nicht den Status 200 haben nicht geloggt werden.

Bzgl. den Parametern, du hättet also gerne, dass URLs ohne die Parameter geloggt werden können?

**Comment by TobiasKrais** [comment]
Danke für die neue Option. Bin schon am testen. Bis jetzt funktioniert sie super!

Danke auch für den Hinweis in den Einstellungen die Option für Status 200. Das ist genau das, was ich gesucht habe.

Und zum eigentlichen Issue: heute Nacht sind alle URLs korrekt gespeichert worden. Auch Chinesische und Russische! Ich glaub den Issue können wir schließen.

Beim Konvertieren der URLs ist mir noch aufgefallen, dass 255 Buchstaben bei URL kodierten URLs zu wenig war. Die URLs wurden abgeschnitten. Eventuell sollte das Feld auf den Typ TEXT erweitert werden oder mehr Buchstaben zugelassen werden. Insbesondere wenn Parameter mitgeloggt werden, kann das schnell mal mehr werden.

**Comment by AndiLeni** [comment]
@TobiasKrais hattest du jetzt noch Probleme mit falsch dekodierten URLs?
Ich habe auch manche Tabellenfelder auf "text" geändert, wird noch etwas abgeschnitten bei dir?

**Comment by TobiasKrais** [comment]
Seit zwei Wochen in der Tat keine falsch kodierten URLs mehr. Problem gelöst. Auch wird nichts mehr abgeschnitten. Vielen Dank!
