### ISSUE TITLE
Bug: Leerzeilen werden erzeugt, wenn weniger Einträge als Zeilen vorliegen

### ISSUE THREAD

**Issue by iceman-fx** [AndiLeni/statistics#54]
Wenn man z.B. bei den Tagesaufrufen als Anzahl 100 wählt, es aber weniger Daten gibt, dann werden die restlichen Tabellezeilen als leere Zeilen dargestellt.

![Unbenannt](https://user-images.githubusercontent.com/4291047/130238199-570e3633-15cd-4cf1-84b8-d43d428fe6d1.PNG)

**Comment by AndiLeni** [comment]
Das ist mehr ein "Feature" als ein Bug. 
Der Code dafür wurde Mal von mir eingefügt, damit die Tabelle immer die selbe Höhe hat. 
Aber ja, ich sehe das es bei vielen Zeilen sehr komisch dargestellt wird.
