### ISSUE TITLE
Wunsch: Zeitraumfilterung auch bei Seitenaufrufen, Verweise, Medien & Kampagnen einfügen

### ISSUE THREAD

**Issue by iceman-fx** [AndiLeni/statistics#55]
... analog der Filterung bei Statistiken

Gern auch mit einer Minianzeige der Einträge "Heute" und "Insgesamt".

**Comment by iceman-fx** [comment]
In der aktuellen Version erhalte ich jetzt nach Auswahl des Zeitraumes (jeweils 25.08.2021) folgende PHP-Fehler:

Notice: Undefined variable: array in redaxo/src/addons/statistics/pages/stats.php on line 66
Warning: array_merge(): Expected parameter 1 to be an array, null given in redaxo/src/addons/statistics/pages/stats.php on line 66
Warning: array_keys() expects parameter 1 to be array, null given in redaxo/src/addons/statistics/pages/stats.php on line 69
Warning: array_values() expects parameter 1 to be array, null given in redaxo/src/addons/statistics/pages/stats.php on line 70

**Comment by iceman-fx** [comment]
Die zeitliche Filterung in den Verweisen wäre auch noch toll.
Dann wäre es komplett bei allen Statistikbereichen drin.

**Comment by AndiLeni** [comment]
@iceman-fx besteht der fehler jetzt auch noch? 
Ich konnte ihn leider nicht replizieren, aber die Filter sind jetzt neu geschrieben und sollten robuster funktionieren.

**Comment by iceman-fx** [comment]
Hi Andi.
Ich habe jetzt die neue Version installiert (Reinstall) und es getestet.

Die Fehler kommen nach wie vor.
Allerdings nur, wenn ich bei beiden Feldern auf "Heute" klicke und filtere.

Notice: Undefined variable: dates_array in redaxo/src/addons/statistics/pages/stats.php on line 40
Warning: array_merge(): Expected parameter 1 to be an array, null given in redaxo/src/addons/statistics/pages/stats.php on line 40
Warning: array_keys() expects parameter 1 to be array, null given in redaxo/src/addons/statistics/pages/stats.php on line 43
Warning: array_values() expects parameter 1 to be array, null given in redaxo/src/addons/statistics/pages/stats.php on line 44
Warning: array_keys() expects parameter 1 to be array, null given in redaxo/src/addons/statistics/pages/stats.php on line 46

**Comment by iceman-fx** [comment]
Ich habe mal in Deinen code geschaut.
Du must vor dem foreach die Variable deklarieren.

```
$dates_array = array();
foreach ($period as $value) {
    $dates_array[$value->format("d.m.Y")] = "0";
}
```

**Comment by iceman-fx** [comment]
Und kannst du bitte die Filterung auch noch bei den Verweisen vorsehen?
