### ISSUE TITLE
Whoops bei Verweise

### ISSUE THREAD

**Issue by skerbis** [AndiLeni/statistics#61]
Error while executing statement "SELECT MIN(date) AS "date" from rex_pagestats_referer": SQLSTATE[42S22]: Column not found: 1054 Unknown column 'date' in 'field list'

**rex_sql_exception:** Error while executing statement "SELECT MIN(date) AS "date" from rex_pagestats_referer": SQLSTATE[42S22]: Column not found: 1054 Unknown column 'date' in 'field list'
**File:** redaxo/src/core/lib/sql/sql.php
**Line:** 449

<details>
<summary>Stacktrace</summary>

| Function                                     | File                                               | Line     |
| -------------------------------------------- | -------------------------------------------------- | -------- |
| rex_sql->setQuery                            | redaxo/src/addons/statistics/lib/helper_filter.php | 83       |
| filter_date_helper->getMinDateFromTable      | redaxo/src/addons/statistics/lib/helper_filter.php | 36       |
| filter_date_helper->__construct              | redaxo/src/addons/statistics/pages/referer.php     | 10       |
| include                                      | redaxo/src/core/lib/packages/package.php           | 280      |
| rex_package->includeFile                     | redaxo/src/core/lib/be/controller.php              | 482      |
| rex_be_controller::{closure}                 | redaxo/src/core/lib/util/timer.php                 | 57       |
| rex_timer::measure                           | redaxo/src/core/lib/be/controller.php              | 483      |
| rex_be_controller::includePath               | redaxo/src/core/lib/be/controller.php              | 432      |
| rex_be_controller::includeCurrentPageSubPath | redaxo/src/addons/statistics/pages/index.php       | 5        |
| include                                      | redaxo/src/core/lib/packages/package.php           | 280      |
| rex_package->includeFile                     | redaxo/src/core/lib/be/controller.php              | 482      |
| rex_be_controller::{closure}                 | redaxo/src/core/lib/util/timer.php                 | 57       |
| rex_timer::measure                           | redaxo/src/core/lib/be/controller.php              | 483      |
| rex_be_controller::includePath               | redaxo/src/core/lib/be/controller.php              | 415      |
| rex_be_controller::includeCurrentPage        | redaxo/src/core/backend.php                        | 233      |
| require                                      | redaxo/src/core/boot.php                           | 141      |
| require                                      | redaxo/index.php                                   | 9        |

</details>
<details>
<summary>System report (REDAXO 5.12.0, PHP 7.4.24, MariaDB 10.2.39)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.12.0     |

| PHP           |            |
| ------------: | :--------- |
|       Version | 7.4.24     |
|       OPcache | yes        |
|        Xdebug | yes        |

| Database      |                 |
| ------------: | :-------------- |
|       Version | MariaDB 10.2.39 |
| Character set | utf8mb4         |

| Server        |            |
| ------------: | :--------- |
|            OS | Linux      |
|          SAPI | fpm-fcgi   |
|     Webserver | Apache     |

| Request       |             |
| ------------: | :---------- |
|       Browser | Safari/15.0 |
|      Protocol | HTTP/1.0    |
|         HTTPS | yes         |

| Packages                    |             |
| --------------------------: | :---------- |
|                     adminer | 1.9.0       |
|               animatedlogin | 0.0.1       |
|                      backup | 2.7.0       |
|                    be_style | 2.12.0      |
|         be_style/customizer | 2.12.0      |
|             be_style/redaxo | 2.12.0      |
|                    be_tools | 1.6.2       |
|                     bloecks | 3.0.2       |
|            bloecks/cutncopy | 3.0.2       |
|           bloecks/dragndrop | 3.0.2       |
|                        cke5 | 4.2.2       |
|             consent_manager | 3.0.0beta9  |
|                     cronjob | 2.8.0       |
|               fa-iconpicker | 0.3 beta    |
|                      ffmpeg | 1.0.0       |
|                  focuspoint | 3.0.2       |
|                  hyphenator | 1.1.7       |
|                     install | 2.9.0       |
|                klxm_website | 2.0.0       |
|                      locked | 1.0.1       |
|                 maintenance | 2.6.2       |
|                      mblock | 3.1.0       |
|               media_manager | 2.11.0      |
|                media_srcset | 2.0.5-dev   |
|                   mediapool | 2.10.0      |
|                    metainfo | 2.8.0       |
|                       mform | 6.0.9       |
|                  mform/docs | 1.1         |
|                     minibar | 2.2.3       |
|            navigation_array | 1.1.1       |
|                    osmproxy | 1.5.0       |
|                      pdfout | 4.0.0       |
|                   phpmailer | 2.10.2      |
|                        plyr | 3.9.0       |
|                     project | dev         |
|            quick_navigation | 5.1.1       |
|                   search_it | 6.7.4       |
|     search_it/documentation | 6.7.3       |
|                       sprog | 1.2.0       |
|                  statistics | 1.0.0-rc.2  |
|                   structure | 2.12.0      |
|           structure/content | 2.12.0      |
|           structure/history | 2.12.0      |
|                    uploader | 2.2.2       |
|                         url | 2.0.0-dev   |
|                       users | 2.8.0       |
|                      watson | 2.2.0       |
|               xoutputfilter | 3.0.0-beta1 |
| xoutputfilter/documentation | 1.0.0       |
|      xoutputfilter/frontend | 3.0.0       |
|                       yform | 3.5.0-dev   |
|                 yform/email | 3.4.1       |
|               yform/manager | 3.4.1       |
|                  yform/rest | 3.4.1       |
|                 yform/tools | 3.4.1       |
|               yform_geo_osm | 1.2.3       |
|       yform_spam_protection | 1.1.0       |
|             yform_usability | 1.4         |
|                    yrewrite | 2.7         |
|    yrewrite_domain_settings | 2.0.1       |
|                 zip_install | 1.1         |

</details>

**Comment by AndiLeni** [comment]
@skerbis gibt es hier noch ein Problem?

**Comment by skerbis** [comment]
@AndiLeni hat sich erledigt , danke 👍🏻

**Comment by AndiLeni** [comment]
Danke für die Rückmeldung :-)
