### ISSUE TITLE
Fehler bei aktueller Beta

### ISSUE THREAD

**Issue by iceman-fx** [AndiLeni/statistics#62]
Folgende Fehler treten auf (frisch installiert):

19.10.2021 09:13:55 | rex_sql_exception | Error while executing statement "INSERT INTO rex_pagestats_data (type,name,count) VALUES("browser","Chrome",1),("os","Android 11",1),("browsertype","Tablet",1),("brand","Samsung",1),("model","Samsung - Galaxy Tab A 10.1" (2019)",1),("date","2021-10-19",1),("hour","09",1),("weekday","2",1)ON DUPLICATE KEY UPDATE count = count + 1;": SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '(2019)",1),("date","2021-10-19",1),("hour","09",1),' at line 6 | redaxo/src/core/lib/sql/sql.php | 449

**Comment by AndiLeni** [comment]
Die einzufügenden Werte werden nun mit Escape-Slashes versehen. 
Bekommst du noch Fehler @iceman-fx?

**Comment by iceman-fx** [comment]
Bei einer Neuinstallation erhalten ich diesen Fehler nicht mehr.
