### ISSUE TITLE
Update auf aktuelle Beta nicht möglich

### ISSUE THREAD

**Issue by iceman-fx** [AndiLeni/statistics#65]
Der Versuch von 1.0.0-rc.2 bzw. 1.0.0-rc.3 auf aktuelle 2.0.0-beta.6 schlägt fehl

AddOn statistics konnte aus folgendem Grund nicht aktualisiert werden:
SQL error: Error while executing statement "ALTER TABLE `rex_pagestats_hash` ADD PRIMARY KEY (`hash`);": SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'fc334cc3a228787f4fd21b6d706ee1a1110061fd' for key 'PRIMARY'

**Comment by AndiLeni** [comment]
Vermutlich sind da noch sehr alte Hashes drin.
Du kannst die Besucher Hashes einfach über die Seite "Einstellungen" löschen und dann das Update probieren, dann sollte es klappen @iceman-fx

**Comment by iceman-fx** [comment]
Ich habe die Besucher-IP-Hashes gelöscht und dann eine Update probiert.

AddOn statistics konnte aus folgendem Grund nicht aktualisiert werden:
SQL error: Error while executing statement "INSERT INTO rex_pagestats_data (type,name,count) VALUES ("model","Amazon - Fire 7"",1);": SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '"Amazon - Fire 7"",1)' at line 2

**Comment by AndiLeni** [comment]
In welcher Datei tritt der fehler auf? @iceman-fx 
Ich dachte, ich hätte die Daten überall escaped.

**Comment by iceman-fx** [comment]
Die Datei kann ich Dir nicht sagen.
Diese Meldung kommt im Installer, wenn man versucht das Update durchzuführen.

Ich teste es aber gern nochmal mit der aktuellen Beta.

**Comment by iceman-fx** [comment]
Nee, auch mit der aktuellen beta7 kommt dieser Fehler beim Update im Installer:

AddOn statistics konnte aus folgendem Grund nicht aktualisiert werden:
SQL error: Error while executing statement "INSERT INTO rex_pagestats_data (type,name,count) VALUES ("browser","aiohttp",9);": SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'browser-aiohttp' for key 'PRIMARY'

**Comment by AndiLeni** [comment]
Das klingt für mich so, als wären durch die vorherigen Update Versuche bereits Daten in die Tabelle geschrieben worden. 
Kannst du die mal händisch leeren und es nochmal versuchen? @iceman-fx

**Comment by iceman-fx** [comment]
Welche Tabellen soll ich leeren?

**Comment by iceman-fx** [comment]
Ich habe jetzt mal händisch die rex_pagestats_data leer gemacht (da standen noch 250 Datensätze drin).
Damit lief das Update durch.
