### ISSUE TITLE
Es wird das AddOn yrewrite ^2.7 benötigt! 

### ISSUE THREAD

**Issue by iceman-fx** [AndiLeni/statistics#77]
Aktuelles statistics kann nicht bei aktueller yrewrite Version (2.8.3) installiert werden.

AddOn statistics konnte aus folgendem Grund nicht installiert werden:
Es wird das AddOn yrewrite ^2.7 benötigt!

**Comment by AndiLeni** [comment]
@iceman-fx Warum hast du das Issue geschlossen?

**Comment by iceman-fx** [comment]
Es kam erst der Fehler, klappte dann aber später doch mit installieren.
Keine Ahnung was da los war.
