### ISSUE TITLE
Ignorierte Seiten führen zu negative Statistiken. 

### ISSUE THREAD

**Issue by skerbis** [AndiLeni/statistics#80]
<img width="1210" alt="Bildschirmfoto 2022-01-13 um 17 03 32" src="https://user-images.githubusercontent.com/791247/149365426-f3b91730-a607-4adb-b005-7a5d1f18f760.png">

**Comment by skerbis** [comment]
und hier auch komisch ... in den letzten Tagen wurden keine weiteren Besucher gezählt.

**Comment by skerbis** [comment]
Nein, im Log steht nichts.

**Comment by alexwenz** [comment]
Hier auch kein Logeintrag aber 3 Wochen keine Zählung.

Hatte einige Pfade unter "Einstellungen / Zu ignorierende Pfade" hinterlegt. Sobald dieses Feld wieder leer ist, funktioniert wieder alles.

**Comment by AndiLeni** [comment]
@alexwenz ich glaube, das tritt auf, wenn du `deine_domain.de` in der Ignorier-Liste hast (als einzelnen Eintrag).
Dann werden nämlich alle aufgerufenen URLs die mit deine_domain.de beginnen (also alle) ignoriert.

Man könnte sich überlegen, ob man hier https://github.com/AndiLeni/statistics/blob/main/lib/stats_visit.php#L111 auf einen identischen String Überprüft statt starts_with.

**Comment by alexwenz** [comment]
Folgende Einträge waren in den Einstellungen für "ignore".

```
www.domain.de/xmlrpc.php
www.domain.de/wp-login.php
www.domain.de/admin
www.domain.de/wp-login.php?wp_lang=en_US
www.domain.de/autodiscover/autodiscover.xml
www.domain.de/.well-known/
www.domain.de/admin.php
www.domain.de/admin/controller/extension/extension/
www.domain.de//wp-json/oembed/1.0/embed?url=https://www.domain.de/
www.domain.de//wp-json/wp/v2/users/
www.domain.de/wp-admin/includes/
```

Vielleicht der Punkt bei ".well-known" oder die Einträge mit den doppelten Slashes?

**Comment by AndiLeni** [comment]
@alexwenz das Problem sollte mit Version 2.2.2 behoben sein. Allerdings nicht für bestehende Fehlerhafte Configs, da musst du manuell nochmal nachgucken ob ein Eintrag passt. Anleitung dazu steht im Changelog :-)

Ich würde dieses Issue dann schließen, aber gerne nochmal kommentieren, falls es immer noch Fehler gibt.
