### ISSUE TITLE
Dashboard Grafiken verschwinden

### ISSUE THREAD

**Issue by HassChristian** [AndiLeni/statistics#83]
![Screenshot 2022-03-10 at 16-21-10 Statistiken · Christian Haß · REDAXO CMS](https://user-images.githubusercontent.com/26849978/157699044-666980eb-efe7-4b68-b87c-32a73b6596f3.png)

Die Grafiken verschwinden nach unbestimmter Zeit.  Der Tageszähler spirngt auf 1 und zählt nicht mehr trotz Traffic auf der Seite

**Comment by AndiLeni** [comment]
Steht denn etwas bei Redaxo im Log? (System -> Logdateien)
Und könntest du im Browser in der Entwicklerkonsole nachschauen, ob es da Fehler im Javascript gibt?

**Comment by HassChristian** [comment]
Okay ich hab was. Im Log stand dieses: mkdir(): Die Datei existiert bereits. Pfad: /redaxo/src/core/lib/util/dir.php

Und in der Konsole zeigt folgendes: Uncaught SyntaxError: unexpected token: ':'  -  index.php 1093:35

**Comment by AndiLeni** [comment]
Ich bin mir nicht sicher, ob das Problem durch dieses addon verursacht wird. Es werden nämlich keine Dateien direkt mit mkdir angelegt. 
Funktionieren andere Addons ohne Probleme? 
Erscheint der Fehler auch beim Besuch anderer Seiten im Backend?

**Comment by HassChristian** [comment]
Das fehlende Semikolon ist nur auf der Startseite in deinem Addon zu finden. Bin alle anderen Seiten des Addons extra durchgegangen. Alle weiteren Addons laufen alle einwandfrei und ohne Probleme.

Habs glaube ich gefunden. Es wird eine IP Adresse mitgezählt. 
`
var stats_chart_visits_185_30_32_71:51434 = {
            x: ["06.03.2022","07.03.2022","08.03.2022","09.03.2022","10.03.2022","11.03.2022","12.03.2022"],
            y: ["0","0","0","0","0","0","1"],
            type: 'line',
            name: 'Aufrufe 185.30.32.71:51434'
        };

var stats_chart_visitors_185_30_32_71:51434 = {
            x: ["06.03.2022","07.03.2022","08.03.2022","09.03.2022","10.03.2022","11.03.2022","12.03.2022"],
            y: ["0","0","0","0","0","0","1"],
            type: 'line',
            name: 'Besucher 185.30.32.71:51434'
        };
`
Oh man, wie finde ich das den jetzt raus, wo die herkommt...???

**Comment by AndiLeni** [comment]
Ah, das erklärt, wieso die Charts nicht mehr funktionieren, aber leider noch nicht, wieso der Zähler bei dir auf 1 stehen bleibt.
`var stats_chart_visitors_185_30_32_71:51434` ist wegen des Doppelpunktes keine gültige Variable. Dazu gibt es schon ein offenes Ticket (#81), bin aber noch nicht dazu gekommen das zu ändern. 

Woher das `mkdir()` kommt kann ich mir noch nicht erklären. Wird denn in der Datenbank weitergezählt wenn du z.B. über Adminer oder phpmyadmin direkt in die Tabellen schaust?
Eventuell ist es nur ein Ausgabeproblem.

**Comment by HassChristian** [comment]
Das mit dem mkdir() gehört vielleicht nicht mit zu deinem Addon.

Ich bin mir nicht sicher, ich meine, dass es meistens passiert, nachdem ich den Suchindex bei search_it erneuert habe. Würde das mal beobachten.

Die Besuche/Besucher werden weitergezählt in der Wochen- und Gesamtstatistik wenn der Besucherzähler auf ein geht.

**Comment by AndiLeni** [comment]
@HassChristian hat sich das Problem mit den Charts in der neuen Version gelöst?

**Comment by HassChristian** [comment]
Hey, das Chartsproblem ist mit der neuen Version weg.

Das die Seitenanrufe und Besucher manchmal auf 1 gehen und nicht mehr weiterzählen konnte ich den aufgelisteten IPs zuordnen.

Mir ist noch etwas aufgefallen. Der Tageszähler für Aufrufe zeigt nur die Hauptdomain an. Alle Subdomains werden nicht mitgezählt bei mir.

**Comment by AndiLeni** [comment]
> Das die Seitenanrufe und Besucher manchmal auf 1 gehen und nicht mehr weiterzählen konnte ich den aufgelisteten IPs zuordnen. Wenn diese erneut aufgerufen werden, geht der Zähler auf 1.

Das kann ich bestätigen. Irgendwo ist der Wurm drin, wenn man mit einer IP auf die Webseite zugreift.

> Mir ist noch etwas aufgefallen. Der Tageszähler für Aufrufe und Besucher zeigt nur die Hauptdomain an. Alle Subdomains werden nicht mitgezählt bei mir.

Welchen Zähler meinst du genau? Das Chart?

**Comment by HassChristian** [comment]
Oh sorry, den Heutezähler unter **Zeitraum filtern** meinte ich.

**Comment by AndiLeni** [comment]
Habe gerade die Version 2.0.1 released, die das beheben sollte.

**Comment by AndiLeni** [comment]
@HassChristian ich schließe das Issue hier mal. Wenn das Problem weiterhin besteht, gerne nochmal melden.
