### ISSUE TITLE
Dashboard Übersicht mit Entwicklung der Zahlen über die letzten Monate

### ISSUE THREAD

**Issue by cukabeka** [AndiLeni/statistics#86]
Wenn ich auf die Subpage komme, sehe ich meist die Statistik über den Gesamt-Zeitraum und die letzten Tage. Die interessieren mich aber meist nur sekundär. Für mich ist die Entwicklung dieses Monats im Vergleich zu den letzten Monaten interessant: Wie entwickelt sich meine Seite in den letzten Monaten? 
Ein Feature, um das ggf hinzuzufügen oder in den Einstellungen vorzugeben, wäre eine tolle Erweiterung.

**Comment by AndiLeni** [comment]
Also du möchtest die Daten und Charts für Besucher und Besuche nicht nur tagesweise sondern auch monatsweise anzeigen lassen können?

**Comment by AndiLeni** [comment]
@cukabeka ist die 2.2.0 mit den tabs für monatlich/jährlich ungefähr so wie du es dir vorgestellt hast?

**Comment by cukabeka** [comment]
Yess! Sehr sehr cool, vielen Dank für das Update!

**Comment by cukabeka** [comment]
Ah, doch noch eine Sache: Wenn ich jetzt die Monatlichen / täglichen / jährlichen Stats noch nach Domains filtern könnte, wäre das toll. So sehe ich ja die Performance für alle Domains gebündelt, mich interessieren aber auch die yrewrite domains, die waren vorher in der Statistik ersichtlich. Das kann auch gerne ein anderer Mechanismus sein als vorher, mit dem das gefiltert werden kann, also z.B. mit einem Dropdown, in dem ich auswählen kann, ob alle domains oder eine bestimmt Domain angezeigt werden.

**Comment by AndiLeni** [comment]
@cukabeka das kannst du jetzt in den Einstellungen aktivieren (`Fasse alle Domains zusammen`).
Ich ging davon aus, dass die meistens nur eine Gesamtanzahl interessiert, weshalb standardmäßig nun zusammengefasst wird :-)
