### ISSUE TITLE
Assets nicht tracken

### ISSUE THREAD

**Issue by alxndr-w** [AndiLeni/statistics#87]
Erstmal: Starkes Addon!

Alle Assets-Ressourcen (css, js, webfonts, ...) werden standardmäßig getrackt. Lassen diese sich pauschal ausklammern?

**Comment by AndiLeni** [comment]
Danke für das Lob :-)

Eigentlich sollten assets nicht getrackt werden. Wo erscheinen sie denn bei dir in der Statistik? Werden sie als Aufruf / Besucher gezählt, oder kommen sie in der "Seiten" Statistik vor?

**Comment by AndiLeni** [comment]
ping @alxndr-w

**Comment by alxndr-w** [comment]
Genau, sie kommen bei den Seitenaufrufen vor: Assets- und Theme-Ordner.

Außerdem wäre es nice, wenn URLs mit get-Parameter irgendwie sinnvoll gruppiert werden könnten - hier läuft bspw. eine Facebook-Kampagne:

![image](https://user-images.githubusercontent.com/3855487/164411580-32c64db2-b343-48ad-abf8-0ba573d63154.png)

**Comment by AndiLeni** [comment]
> Genau, sie kommen bei den Seitenaufrufen vor: Assets- und Theme-Ordner.  

Das ist sehr merkwürdig, ich kann das bei mir nicht feststellen oder reproduzieren.
Kannst du eine URL hier reinstellen, so wie sie in der Statistik „Seitenaufrufe“ aufgeführt wird?

> Außerdem wäre es nice, wenn URLs mit get-Parameter irgendwie sinnvoll gruppiert werden könnten - hier läuft bspw. eine Facebook-Kampagne:

Dafür kannst du die Option "Ignoriere URL-Parameter" aktivieren. Damit werden Urls nur ohne Parameter gespeichert.
![grafik](https://user-images.githubusercontent.com/13385771/164498475-449fe74c-a77a-4150-a85e-6b7db07e7d79.png)

**Comment by alxndr-w** [comment]
> Kannst du eine URL hier reinstellen, so wie sie in der Statistik „Seitenaufrufe“ aufgeführt wird?

Gerne via Slack per Direktnachricht

> Dafür kannst du die Option "Ignoriere URL-Parameter" aktivieren. Damit werden Urls nur ohne Parameter gespeichert.

Ei, das habe ich übersehen.

**Comment by alxndr-w** [comment]
Das müsste ich mir nochmal ansehen, ich habe das Addon pro forma im Einsatz, schaue aber nicht rein. Danke für die Erinnerung.

**Comment by AndiLeni** [comment]
ping @alxndr-w

**Comment by alxndr-w** [comment]
Ich kann mich darum gerade nicht kümmern, würde mich aber nochmal melden.
