### ISSUE TITLE
Kampagnen-Funktion anders erklären

### ISSUE THREAD

**Issue by cukabeka** [AndiLeni/statistics#91]
Ich verstehe noch nicht, wie ich kampagnen einrichtet. Vielleicht kann man das noch irgendwie anders erklären. Ich brauche also ein Modul, aber wofür gebe ich REX_VALUE_1 an? Ist das die Kampagne? Ich fände einen Screenshot o.ä. in der Hilfe sehr nützlich.

Du hast mir ja dazu erläutert:

> das was man mit dem plugin "kampagnen" machen kann ist es, auf events im frontend zu reagieren.z.b. klickt ein nutzer auf den "buchen" button, dann kann im js ein aufruf zu der kampagnen api gemacht werden um zu sehen, wie häufig der "buchen" button gedrückt wurde. z.b. um einen überblick zu erhalten wie die differenz ist zwischen "button geklickt" und "artikel gekauft"

Das ist schon mal sehr hilfreich, vielleicht kann das direkt auf die Kampagnen Page.

Interessant wäre noch, tracking-Ziele zu tracken. Wenn ich z.b. an eine URL ein '?stat_track_origin=qr-code-22' o.ä. dranhängen kann, wäre das ein großer Mehrwert. Das ist ja ein wenig anders als die aktuelle Funktion, um eine Button Performance zu tracken.

**Comment by VIEWSION** [comment]
Eigentlich ist es eher ein Event-Tracking. Man hat nur den Parameter "name" und kann damit z.B. ein Absenden eines Formulars mitzählen. Für ein Kampagnen-Tracking fehlt meiner Meinung nach noch die Relation zum Besucher... Ich muss die Besucher z.B. erst über einer ref Parameter einer Kampagne zuordnen (z.B. Besucher kommt vom Newsletter X) und dann müsste ich sehen können wie viele Newsletter Besucher dann das Formular abgesendet haben im Verhältnis zu allen anderen Besuchern die nicht über den Newsletter gekommen sind. Das Naming ist also aktuell etwas irreführend. Ein echtes Kampagnen-Tracking wäre aber MEGA! Aber auch ohne Kampagnen-Tracking ist das AddOn sehr nützlich und für die meisten Anforderungen völlig ausreichend.

**Comment by cukabeka** [comment]
Absolut, dem stimme ich voll zu - mega nützlich, das Addon. Auch ein Event-Tracking wäre super. Vielleicht alles hauptsächlich eine Wording-Frage.

**Comment by alxndr-w** [comment]
@cukabeka ich habe das Feature in diesem Addon selbst noch nicht ausprobiert.

Nur wenn, dann sollten die Dinge best practice sein und nicht was eigenes für die Aufgabe ausgedacht werden.

**Comment by AndiLeni** [comment]
@cukabeka Genau das was du beschrieben hast macht das Addon NICHT 😅
  Es ist ein einfaches logging um Events die in redaxo oder im frontend passieren zu erfassen. 

Mit `?rex-api-call=stats` wird z.b. kein Artikel angezeigt. Es ist lediglich dafür gedacht via JS Ereignisse zu erfassen, z.b. wenn ein Formular via JS abgesendet wird.
Im backend gibt es dafür das Äquivalent mittels `Event::log("my_event_name");`.

Ein Link wie etwa `redaxo.com/mein-artikel?stats_canpaignname=WhatsAppGruppe_XY-2024-11` ist aktuell nicht vorgesehen, denn du kannst im Addon bereits jetzt einfach nach url filtern und gucken, an welchen Tagen dieser Link wie oft aufgerufen wurde 🙂

**Comment by cukabeka** [comment]
😅 Damn, dass es das genau nicht macht - aber okay, dann danke für die Klärung. Das mit dem Filter schaue ich mir nochmal an, finde es halt nicht so komfortabel um auszuwerten und zu vergleichen, wenn ich zB verschiedene Kanäle vergleichen will. Evtl baue ich mir sonst selber mal was wie ich mir das vorstelle und schicke dann einen Pull Request.

**Comment by cukabeka** [comment]
Und @AndiLeni deine Erklärung ist evtl genau das, was mit in die readme könnte, das macht die Verwendung von Events für mich klarer.
