### ISSUE TITLE
Safari Mac wird als Windows 10 chrome erkannt? 

### ISSUE THREAD

**Issue by skerbis** [AndiLeni/statistics#95]
<img width="1125" alt="Bildschirmfoto 2022-08-31 um 14 20 03" src="https://user-images.githubusercontent.com/791247/187677068-8f6a99d5-fe31-4135-97cb-3bdfe6f5ccd1.png">

**Comment by AndiLeni** [comment]
Danke fürs melden, 
Steht es nur im Dashboard so, oder auch auf der Seite des add-ons? 
Vllt reicht es auch schon, den vendor zu aktualisieren.

**Comment by skerbis** [comment]
Ja auch auf den Seiten des AddOns

**Comment by skerbis** [comment]
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15

**Comment by AndiLeni** [comment]
Bei mir wird damit korrekt ein Safari auf Mac OS erfasst 🤔

**Comment by skerbis** [comment]
hmm strange. Ok. Evtl. liegt es hier auch an einer lokalen Geschichte ich forsche mal weiter.

**Comment by AndiLeni** [comment]
Ich schließe hier mal, melde dich, wenn es weiterhin Erkennungsprobleme gibt.
