### ISSUE TITLE
www.domain.de & domain.de zusammenfassen

### ISSUE THREAD

**Issue by iceman-fx** [AndiLeni/statistics#99]
Option zum Zusammenfassen der Domain mit und ohne www. bereitstellen, damit diese Domains nicht separat in der Statistik und den Graphen aufgeführt wird.

**Comment by AndiLeni** [comment]
Dazu dann die Frage, was mit anderen Subdomains passieren soll? 
Eine Option, um alle Subdomains auszufiltern? Einzelne Subdomains angeben, die entfernt werden sollen?

**Comment by iceman-fx** [comment]
Eher das Zusammenfassen von www und nicht-www.
Bei den meisten Webservern ist std,mäßig www und nicht-www das gleiche Webspace-Ziel = Homepage.
Meist leitet eine Version dieser Aufrufe eh nur auf den anderen um.

Daher wäre eine Option (Checkbox) ganz gut, um diese beiden zusammenfassen zu können.

**Comment by iceman-fx** [comment]
Habe gerade die aktuelle v3.x installiert.

Dort ist ja bereits eine Zusammenfassen-Funktion drin, aber leider etwas unglücklich umgesetzt.
Diese fasst alle Domains zusammen, egal ob www./non-www/... oder richtige Domains (MultiSite-Umgebung).

Besser wäre es, wenn man 3 Optionen hätte:
1. wirklich alle Domains zusammenfassen (Besucher Gesamt | ...)
2. nichts zusammenfassen (Ausgabe: domain1.de | www.domain1.de | domain2.de | www.domain2.de | www.domain2.de:443 | ...)
3. nur die Domains mitsamt Subdomain www./xyz. & Ports :xyz zusammenfassen (Ausgabe: domain1.de | domain2.de | ...)

Auch werden neuerdings Domains mit Portnummer gesondert aufgeführt, was eigentlich unnötig ist:

![1](https://github.com/AndiLeni/statistics/assets/4291047/a683adc9-8fa9-4ca7-9580-a293a785af19)

**Comment by iceman-fx** [comment]
Deswegen ja eine Auswahl bereitstellen, so dass der Admin es selbst entscheiden kann.
In meinem Fall muss ich halt immer erst unzählige Male klicken, damit ich nur die Übersicht der einen Präsenz sehe.

Evtl. macht es Sinn, dass man eine Selectbox hat, wo std.mäßig "- Alle Domains -" gewählt ist, man dann aber auch nur die jeweilige Hauptdomain (= fasst alles dieser Domain zusammen (www. + ohne www)) auswählen kann.
